export type NativeAndroidBodyTemperatureMeasurementLocation =
  | 'unspecified'
  | 'armpit'
  | 'finger'
  | 'forehead'
  | 'mouth'
  | 'rectum'
  | 'temporalArtery'
  | 'toe'
  | 'ear'
  | 'wrist'
  | 'vagina'

export type NativeIOSBodyTemperatureSensorLocation =
  | 'other'
  | 'armpit'
  | 'body'
  | 'ear'
  | 'finger'
  | 'gastroIntestinal'
  | 'mouth'
  | 'rectum'
  | 'toe'
  | 'earDrum'
  | 'temporalArtery'
  | 'forehead'
