/**
 * Normalized workout activity type returned by {@linkcode NitroHealth.readWorkouts}.
 *
 * Values are mapped natively from `HKWorkoutActivityType` (iOS) and
 * `ExerciseSessionRecord.EXERCISE_TYPE_*` (Android). Equipment/location
 * sub-variants fold into the parent activity (treadmill → `running`,
 * stationary bike → `cycling`, pool/open water → `swimming`, individual
 * dumbbell/barbell exercises → `strengthTraining`). Platform values with no
 * cross-platform equivalent map to `'other'`; unknown future values are
 * reported separately through `WorkoutActivity.status`. Some members are only ever emitted by one platform
 * (for example `archery` on iOS, `paragliding` on Android).
 */
export type WorkoutActivityType =
  | 'americanFootball'
  | 'archery'
  | 'australianFootball'
  | 'badminton'
  | 'barre'
  | 'baseball'
  | 'basketball'
  | 'bowling'
  | 'boxing'
  | 'calisthenics'
  | 'climbing'
  | 'coreTraining'
  | 'cricket'
  | 'crossTraining'
  | 'curling'
  | 'cycling'
  | 'dance'
  | 'discSports'
  | 'elliptical'
  | 'equestrianSports'
  | 'fencing'
  | 'fishing'
  | 'fitnessGaming'
  | 'flexibility'
  | 'golf'
  | 'gymnastics'
  | 'handball'
  | 'handCycling'
  | 'highIntensityIntervalTraining'
  | 'hiking'
  | 'hockey'
  | 'hunting'
  | 'jumpRope'
  | 'kickboxing'
  | 'lacrosse'
  | 'martialArts'
  | 'mindAndBody'
  | 'mixedCardio'
  | 'other'
  | 'paddleSports'
  | 'paragliding'
  | 'pickleball'
  | 'pilates'
  | 'racquetball'
  | 'rowing'
  | 'rugby'
  | 'running'
  | 'sailing'
  | 'skating'
  | 'skiing'
  | 'snowboarding'
  | 'snowSports'
  | 'soccer'
  | 'softball'
  | 'squash'
  | 'stairClimbing'
  | 'stepTraining'
  | 'strengthTraining'
  | 'surfing'
  | 'swimBikeRun'
  | 'swimming'
  | 'tableTennis'
  | 'taiChi'
  | 'tennis'
  | 'trackAndField'
  | 'underwaterDiving'
  | 'volleyball'
  | 'walking'
  | 'waterFitness'
  | 'waterPolo'
  | 'waterSports'
  | 'wheelchair'
  | 'wrestling'
  | 'yoga'
